# Generated by Django 4.1.4 on 2022-12-16 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('category', models.CharField(choices=[('Food', 'Food'), ('Drink', 'Drink'), ('Other', 'Other')], default='Food', max_length=100)),
                ('created_dt', models.DateTimeField(auto_now_add=True)),
                ('updated_dt', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['created_dt'],
            },
        ),
    ]
