# Generated by Django 4.1.4 on 2022-12-19 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_employee_alter_menu_options_alter_restaurant_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_dt', models.DateTimeField(auto_now_add=True)),
                ('updated_dt', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.employee')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.restaurant')),
            ],
            options={
                'ordering': ['created_dt'],
            },
        ),
    ]
