# Generated by Django 4.1.3 on 2022-12-20 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_vote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='restaurant',
        ),
        migrations.AddField(
            model_name='vote',
            name='menu',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='management.menu'),
        ),
    ]
