version: '3.10'

services:
  web:
    restart: on-failure
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    volumes:
      - .:/app
    env_file:
      - .env
    networks:
      - voting-network
    container_name: voting_container

networks:
  voting-network:
    driver: bridge